### ISSUE TITLE
strptime not implement

### ISSUE THREAD

**Issue by comicfans** [oracle/fastr#29]
just run strptime('2013-04-04','%Y-%m-%d'), fastR throws error

Fri Nov 09 19:43:57 CST 2018
com.oracle.truffle.r.runtime.RInternalError: java.time.zone.ZoneRulesException: Unknown time-zone ID: CST
	at com.oracle.truffle.r.nodes.function.FunctionDefinitionNode.execute(FunctionDefinitionNode.java:321)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:289)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:278)

full log here:
[fastr_errors_pid22716.log](https://github.com/oracle/fastr/files/2565707/fastr_errors_pid22716.log)

**Comment by steve-s** [comment]
Hi comicfans,

thanks for reporting this issue. We can reproduce and the fix should be available soon. In the meantime you can run FastR with environment variable `TZ` set to `CST6CDT`, e.g. `TZ=CST6CDT graalvm/bin/R`.

**Comment by steve-s** [comment]
seems that the "CST" abbreviation is interpreted differently by the system libraries and Java, so the fix will not be that easy. Out of curiosity, what timezone do you intend to use?

**Comment by comicfans** [comment]
Hi steve,

I want to use +0800 (Asia/Shanghai) timezone , my linux timedatectl  output:

               Local time: Sat 2018-11-10 11:10:37 CST
           Universal time: Sat 2018-11-10 03:10:37 UTC
                  Time zone: Asia/Shanghai (CST, +0800)
