### ISSUE TITLE
Java interop - Calling R functions from Java code

### ISSUE THREAD

**Issue by mardukbp** [oracle/fastr#96]
The [Java Parallel Optimization Package](http://www5.cs.fau.de/research/software/java-parallel-optimization-package/) provides a pure-Java implementation of the UNCMIN algorithms used by the `nlm` function of the R package `stats`. In particular, JPOP enables the parallel evaluation of analytical functions, gradients, and Hessians, with multi-core optimization of computationally expensive functions.

I want to write an R function `parnlm` that provides a FastR interface to this package. Since the function to be optimized is defined in R, I would like to know how to pass an R function as an argument to a Java function. Maybe it involves compiling the function to Java bytecode?

**Comment by steve-s** [comment]
Hello Marduk,

the infrastructure can convert R functions to Java functional interfaces and vice versa. So for example:

```
public class MyJavaClass {
  public int sumRFunction(java.util.function.Function<Integer,Integer> lambda) {
    int res = 0;
    for (int i = 0; i < 10; ++i) {
      res += lambda.apply(i);
    }
    return res;
  }
}
```

and in R

```
> testObject <- new("MyJavaClass")
> testObject$sumRFunction(function(i) i*2L)
[1] 90
``` 

we should add this to our documentation. In case you weren't aware of the sources of the documentation for Java interop: [this example](https://github.com/graalvm/examples/tree/master/r_java_bench) may be useful and there is documentation at [graalvm.org](https://www.graalvm.org/docs/reference-manual/languages/r/#graalvm-integration) and in [our repo](https://github.com/oracle/fastr/blob/master/documentation/tutorials/interop/javaInteroperability.md).

**Comment by steve-s** [comment]
Btw. this looks like a very neat use-case for FastR: the interaction with Java should be both simpler and much much faster. If you can, let us know how this went.

**Comment by mardukbp** [comment]
Thank you Stepan! However, my use case is a little bit more complex. My R function takes a double vector as input and returns a double.

I tried the following:

```Java
public class MyJavaClass {
  public Double func(java.util.function.Function<Double[],Double> lambda) {
      double[] arr = {1,2,3};
      Double[] arrD = new Double[arr.length];

      for (int i = 0; i < arr.length; i++) {
	  arrD[i] = Double.valueOf(arr[i]);
      }
    
    return lambda.apply(arrD);
  }
}
```

```R
MyJavaClass <- new("MyJavaClass")
MyJavaClass$func(function(v) v[[1]])
```

and obtained the following error:

````
Error in polyglot evaluation : Error in FUN(...) : unused arguments (, )
	at com.oracle.truffle.polyglot.PolyglotFunction.apply(PolyglotFunction.java:66)
	at MyJavaClass.func(MyJavaClass.java:11)
```

What am I doing wrong?

**Comment by mardukbp** [comment]
Thank you Stepan! I have been thinking that FastR can provide an interactive interface to the hundreds of Java packages developed in academia in the last 20 years. I will experiment with JPOP and SSJ and report back.

**Comment by steve-s** [comment]
Sounds really interesting! Btw. if you need your Java `Function` to take/return something that cannot be expresses as Java type or is dynamic (sometimes this type, sometimes another), then you can always use `java.util.function.Function<Object, Object>`.

**Comment by mardukbp** [comment]
Yes, thanks. For reference, [here](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html) is the documentation for the built-in functional interfaces. This issue should be discussed in [Java interoperability](https://github.com/oracle/fastr/blob/master/documentation/tutorials/interop/javaInteroperability.md). Until this is done, I would suggest reopening the issue just to remember that something is pending.

**Comment by steve-s** [comment]
> I would suggest reopening the issue just to remember that something is pending.

indeed, good idea.
